GET http://localhost:5050/logs
Content-Type: application/json

###

POST http://localhost:5050/logs/batch
Content-Type: application/json

  {
    "pathname": "/api/users",
    "method": "GET",
    "status_code": 200,
    "duration": 87,
    "started_at": "2025-05-28T13:00:15.123Z"
  }

###

POST http://localhost:5050/logs/batch
Content-Type: application/json

{    
    "pathname": "/api/products",
    "method": "POST",
    "status_code": 201,
    "duration": 134,
    "started_at": "2025-05-28T13:00:16.891Z"
}